/* tslint:disable */
/* eslint-disable */
/**
 * Business Accounting API
 * The API for the business accounting
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Transaction } from './transaction';
/**
 * 
 * @export
 * @interface Receipt
 */
export interface Receipt {
    /**
     * 
     * @type {number}
     * @memberof Receipt
     */
    idReceipt: number;
    /**
     * 
     * @type {string}
     * @memberof Receipt
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Receipt
     */
    dateReceipt: string;
    /**
     * 
     * @type {Transaction}
     * @memberof Receipt
     */
    transaction: Transaction;
}
