/* tslint:disable */
/* eslint-disable */
/**
 * Business Accounting API
 * The API for the business accounting
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    idTransaction: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    product: string;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    unit: string;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    amount: number;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    cashIn: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Transaction
     */
    cashOut: boolean;
}
